/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Class.Koneksi;
import Java.Connect;
import Java.ListPegawai;
import Java.modelTabelPegawai;
import java.awt.BorderLayout;
import java.awt.Container;
import java.beans.PropertyChangeEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.sql.*;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.beans.PropertyChangeListener;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Dii
 */
public class Laporan_Pembelian extends javax.swing.JFrame {

    //object
    private Connect connection;
    private ResultSet hasil;
    private DefaultTableModel model;
    private Date tglHariIni;
    private SimpleDateFormat formatTanggal;
    private Date tempDate;
    
    /**
     * Creates new form Laporan_Penjualan
     */
    public Laporan_Pembelian() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        tglHariIni = new Date();
        formatTanggal = new SimpleDateFormat("yyyy-MM-dd");
        tgl_awal.setDate(tglHariIni);
        tgl_akhir.setDate(tglHariIni);
        System.out.println(formatTanggal.format(tglHariIni));
        cek();
//        loadLaporan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        tgl_awal = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tgl_akhir = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );

        jCheckBox1.setText("Tanggal");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });

        tgl_awal.setDateFormatString("MM-dd-yyyy");
        tgl_awal.setEnabled(false);
        tgl_awal.getDateEditor().addPropertyChangeListener(new PropertyChangeListener()
            {
                @Override
                public void propertyChange(PropertyChangeEvent e)
                {
                    if ("date".equals(e.getPropertyName()))
                    {
                        tempDate = (Date) e.getNewValue();
                        formatTanggal.format(tempDate);
                        System.out.println(e.getPropertyName()
                            + ": " + (Date) e.getNewValue());
                    }
                }
            });
            tgl_awal.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    tgl_awalKeyPressed(evt);
                }
            });

            jLabel1.setText("s.d");

            jButton1.setText("Lihat");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            tgl_akhir.setDateFormatString("MM-dd-yyyy");
            tgl_akhir.setEnabled(false);
            tgl_akhir.getJCalendar().setMinSelectableDate(tempDate);
            tgl_akhir.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    tgl_akhirKeyPressed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jCheckBox1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tgl_awal, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tgl_akhir, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(jButton1)
                            .addGap(0, 297, Short.MAX_VALUE))
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tgl_awal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox1)
                            .addComponent(jLabel1)
                            .addComponent(jButton1))
                        .addComponent(tgl_akhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void tgl_awalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tgl_awalKeyPressed
        int key = evt.getKeyCode();
        if (key == 10) {
            tgl_awal.requestFocus();
        }
    }//GEN-LAST:event_tgl_awalKeyPressed
    
    private void tgl_akhirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tgl_akhirKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_akhirKeyPressed

    private void cek(){
        String tgl = formatTanggal.format(tglHariIni);
        String query = "SELECT b.kode_barang,\n" +
            "	s.nama_supplier,\n" +
            "	p.no_faktur_pembelian,\n" +
            "	b.nama_barang,\n" +
            "	dp.jumlah_barang,\n" +
            "	k.nama_konversi,\n" +
            "	b.harga_beli,\n" +
            "	dp.discon_persen,\n" +
            "	dp.discon_rp,\n" +
            "	p.tgl_pembelian\n" +
            "	FROM pembelian p\n" +
            "	JOIN detail_pembelian dp on dp.no_faktur_pembelian = p.no_faktur_pembelian\n" +
            "	JOIN supplier s on s.kode_supplier = p.kode_supplier\n" +
            "	JOIN barang b on b.kode_barang = dp.kode_barang\n" +
            "	JOIN barang_konversi bkv on bkv.kode_barang_konversi = dp.kode_konversi\n" +
            "	JOIN konversi k on k.kode_konversi=bkv.kode_konversi\n" +
            "   Where DATE_FORMAT(p.tgl_pembelian, '%Y-%m-%d') = \"" +tgl+"\""+
            "	order by p.kode_supplier and dp.no_faktur_pembelian ASC";
        HashMap params = null;
            loadLaporan(query,params);
    }
    
    private void loadLaporan(){
        try {
            Connect koneksi = new Connect();
           Connection conn = koneksi.conn;
            JasperDesign jd =JRXmlLoader.load(new File("").getAbsolutePath()+"/src/Laporan/Laporan_Pembelian_Hari_Ini.jrxml");
            String query = "SELECT p.kode_supplier,s.nama_supplier,dp.kode_barang,b.nama_barang,dp.jumlah_barang,kv.nama_konversi,"
                    + "dp.harga_pembelian,dp.discon_persen,dp.discon_rp,   p.kode_pembelian,dp.no_faktur_pembelian,DATE_FORMAT(p.tgl_pembelian,"
                    + " '%Y-%m-%d') tgl_pembelian, p.no_faktur_pembelian FROM pembelian p join detail_pembelian dp ON p.kode_pembelian="
                    + "dp.id_detail_pembelian join supplier s on s.kode_supplier=p.kode_supplier join barang b on b.kode_barang="
                    + "dp.kode_barang join barang_konversi bkv on bkv.kode_barang_konversi=dp.kode_konversi, konversi kv where "
                    + "kv.kode_konversi=bkv.kode_konversi and p.tgl_pembelian = CURRENT_DATE order by p.kode_supplier and "
                    + "dp.no_faktur_pembelian";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(query);
            jd.setQuery(newQuery);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            
            JasperPrint print = JasperFillManager.fillReport(jr, null,conn);
            
            //JasperPrintManager.printReport(print, false);
            JasperViewer viewer = new JasperViewer(print);
            System.out.println("sukses");
            jPanel2.removeAll();
            jPanel2.setLayout(new BorderLayout());
            jPanel2.repaint();
            jPanel2.add(new JRViewer(print));
////            show_report.repaint();
            jPanel2.revalidate();

        } catch (JRException ex) {
            Logger.getLogger(Laporan_Pembelian.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void loadLaporan(String query, HashMap params){
        try {
            System.out.println(query);
            Connect koneksi = new Connect();
           Connection conn = koneksi.conn;
            JasperDesign jd =JRXmlLoader.load(new File("").getAbsolutePath()+"/src/Laporan/Laporan_Pembelian_Final.jrxml");
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(query);
            jd.setQuery(newQuery);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            JasperPrint print = JasperFillManager.fillReport(jr, params,conn);
            //JasperPrintManager.printReport(print, false);
            JasperViewer viewer = new JasperViewer(print);
            System.out.println("sukses");
            jPanel2.removeAll();
            jPanel2.setLayout(new BorderLayout());
            jPanel2.repaint();
            jPanel2.add(new JRViewer(print));
////            show_report.repaint();
            jPanel2.revalidate();

        } catch (JRException ex) {
            Logger.getLogger(Laporan_Pembelian.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Date awal = tgl_awal.getDate();
        Date akhir = tgl_akhir.getDate();
        String awalDalem = formatTanggal.format(awal);
        String akhirDalem = formatTanggal.format(akhir);
        HashMap params = new HashMap();
        params.put("awal", awal);
        params.put("akhir", akhir);
        String query = "SELECT b.kode_barang,\n" +
            "s.nama_supplier,\n" +
            "p.no_faktur_pembelian,\n" +
            "b.nama_barang,\n" +
            "dp.jumlah_barang,\n" +
            "k.nama_konversi,\n" +
            "b.harga_beli,\n" +
            "dp.discon_persen,\n" +
            "dp.discon_rp,\n" +
            "p.tgl_pembelian\n" +
            "FROM pembelian p\n" +
            "JOIN detail_pembelian dp on dp.no_faktur_pembelian = p.no_faktur_pembelian\n" +
            "JOIN supplier s on s.kode_supplier = p.kode_supplier\n" +
            "JOIN barang b on b.kode_barang = dp.kode_barang\n" +
            "JOIN barang_konversi bkv on bkv.kode_barang_konversi = dp.kode_konversi\n" +
            "JOIN konversi k on k.kode_konversi=bkv.kode_konversi\n" +
            "   Where DATE_FORMAT(p.tgl_pembelian, '%Y-%m-%d') between \"" +awalDalem+"\" and \""+akhirDalem+"\"\n" +
            "order by p.kode_supplier and dp.no_faktur_pembelian ASC";
        System.out.println(awalDalem+" dan "+akhirDalem);
        loadLaporan(query,params);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        if (jCheckBox1.isSelected()) {
            tgl_awal.setEnabled(true);
            tgl_akhir.setEnabled(true);
        }else{
            tgl_awal.setEnabled(false);
            tgl_akhir.setEnabled(false);
            loadLaporan();
        }
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laporan_Pembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser tgl_akhir;
    private com.toedter.calendar.JDateChooser tgl_awal;
    // End of variables declaration//GEN-END:variables
}
