/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Class.Koneksi;
import Java.Connect;
import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.InputStream;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;



/**
 *
 * @author User
 */
public class Master_BarangDatang extends javax.swing.JFrame {

    
    private SimpleDateFormat formatTanggal;
    private Connect connection;

    private Date tempDate, tglHariIni, awal,akhir;
    private String awal1, akhir1;
    
    /**
     * Creates new form NewJFrame
     */
    public Master_BarangDatang() {
        initComponents();
        this.setLocationRelativeTo(null);
        tglHariIni = new Date();
        formatTanggal = new SimpleDateFormat("yyyy-MM-dd");
        tgl_awal.setDate(tglHariIni);
        tgl_akhir.setDate(tglHariIni);
        lihat();
        
    }
    
    private void cek(){
        String tgl = formatTanggal.format(tglHariIni);
        String query = "SELECT dp.kode_barang,\n" +
            "b.nama_barang,\n" +
            "dp.jumlah_barang,\n" +
            "kv.nama_konversi,\n" +
            "dp.hj1,\n" +
            "dp.hj2,\n" +
            "p.tgl_pembelian\n" +
            "FROM detail_pembelian dp\n" +
            "JOIN barang b on b.kode_barang = dp.kode_barang\n" +
            "JOIN barang_konversi bkv on bkv.kode_barang_konversi = dp.kode_konversi\n" +
            "JOIN konversi kv on kv.kode_konversi = bkv.kode_konversi\n" +
            "JOIN pembelian p on p.no_faktur_pembelian=dp.no_faktur_pembelian\n"+
            " Where DATE_FORMAT(p.tgl_pembelian, '%Y-%m-%d') = \"" +tgl+"\"";
            //lihat(query);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        comKelompok = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        tgl_awal = new com.toedter.calendar.JDateChooser();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        tgl_akhir = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setToolTipText("");

        comKelompok.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Masukkan Nama Kelompok Barang --" }));
        loadNamaKelompok();

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/if_yast_printer_30297.png"))); // NOI18N
        jButton1.setText("Print");

        tgl_awal.setDateFormatString("dd-MM-yyyy");
        tgl_awal.setEnabled(false);
        tgl_awal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tgl_awalKeyPressed(evt);
            }
        });

        jCheckBox1.setText("Tanggal");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });

        jButton2.setText("Lihat");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton2KeyTyped(evt);
            }
        });

        tgl_akhir.setDateFormatString("dd-MM-yyyy");
        tgl_akhir.setEnabled(false);
        tgl_akhir.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tgl_akhirPropertyChange(evt);
            }
        });
        tgl_akhir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tgl_akhirKeyPressed(evt);
            }
        });

        jLabel2.setText("s.d");

        jPanel1.setPreferredSize(new java.awt.Dimension(801, 280));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(comKelompok, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tgl_awal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tgl_akhir, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 3, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comKelompok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgl_akhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgl_awal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addComponent(jCheckBox1)))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(975, 592));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tgl_awalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tgl_awalKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tgl_akhir.requestFocusInWindow();
            System.out.println(tgl_akhir.requestFocus(true));
        }
    }//GEN-LAST:event_tgl_awalKeyPressed

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        if (jCheckBox1.isSelected()) {
            tgl_awal.setEnabled(true);
            tgl_akhir.setEnabled(true);
            System.out.println("cekbox enabled");
        }else{
            tgl_awal.setEnabled(false);
            tgl_akhir.setEnabled(false);
            tgl_awal.setDate(tglHariIni);
            tgl_akhir.setDate(tglHariIni);
            
        }
        
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        lihat();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void lihat(){
        System.out.println("Print an");
        Date awalDalem = tgl_awal.getDate();
        Date akhirDalem = tgl_akhir.getDate();
        HashMap params = new HashMap<String, Date>();
        String awal1Dalem = formatTanggal.format(awalDalem);
        String akhir1Dalem = formatTanggal.format(akhirDalem);
        boolean status = jCheckBox1.isSelected();
        String query = null;
        if (status) {
            params.put("awal",awalDalem);
            params.put("akhir", akhirDalem);
            String kelompok = comKelompok.getSelectedItem().toString();
            if(kelompok!="-- Masukkan Nama Kelompok Barang --"){
                query = "SELECT dp.kode_barang,\n" +
                    "b.nama_barang,\n" +
                    "dp.jumlah_barang,\n" +
                    "kv.nama_konversi,\n" +
                    "dp.hj1,\n" +
                    "dp.hj2,\n" +
                    "kk.nama_kelompok,\n" +
                    "p.tgl_pembelian\n" +
                    "FROM detail_pembelian dp\n" +
                    "JOIN barang b on b.kode_barang = dp.kode_barang\n" +
                    "JOIN barang_konversi bkv on bkv.kode_barang_konversi = dp.kode_konversi\n" +
                    "JOIN konversi kv on kv.kode_konversi = bkv.kode_konversi\n" +
                    "JOIN pembelian p on p.no_faktur_pembelian=dp.no_faktur_pembelian\n" +
                    "JOIN kelompok kk on kk.id_kelompok = b.id_kelompok\n" +
                    "WHERE kk.nama_kelompok = \""+kelompok+"\"";
            }else{
                query = "SELECT dp.kode_barang,\n" +
                    "b.nama_barang,\n" +
                    "dp.jumlah_barang,\n" +
                    "kv.nama_konversi,\n" +
                    "dp.hj1,\n" +
                    "dp.hj2,\n" +
                    "kk.nama_kelompok,\n" +
                    "p.tgl_pembelian\n" +
                    "FROM detail_pembelian dp\n" +
                    "JOIN barang b on b.kode_barang = dp.kode_barang\n" +
                    "JOIN barang_konversi bkv on bkv.kode_barang_konversi = dp.kode_konversi\n" +
                    "JOIN konversi kv on kv.kode_konversi = bkv.kode_konversi\n" +
                    "JOIN pembelian p on p.no_faktur_pembelian=dp.no_faktur_pembelian\n" +
                    "JOIN kelompok kk on kk.id_kelompok = b.id_kelompok";
            }
        }else{
            String tgl = formatTanggal.format(tglHariIni);
            params = null;
            String kelompok = comKelompok.getSelectedItem().toString();
            if(kelompok!="-- Masukkan Nama Kelompok Barang --"){
                query = "SELECT dp.kode_barang,\n" +
                    "b.nama_barang,\n" +
                    "dp.jumlah_barang,\n" +
                    "kv.nama_konversi,\n" +
                    "dp.hj1,\n" +
                    "dp.hj2,\n" +
                    "kk.nama_kelompok,\n" +
                    "p.tgl_pembelian\n" +
                    "FROM detail_pembelian dp\n" +
                    "JOIN barang b on b.kode_barang = dp.kode_barang\n" +
                    "JOIN barang_konversi bkv on bkv.kode_barang_konversi = dp.kode_konversi\n" +
                    "JOIN konversi kv on kv.kode_konversi = bkv.kode_konversi\n" +
                    "JOIN pembelian p on p.no_faktur_pembelian=dp.no_faktur_pembelian\n" +
                    "JOIN kelompok kk on kk.id_kelompok = b.id_kelompok\n" +
                    "WHERE kk.nama_kelompok = \""+kelompok+"\" and \n"
                        + "DATE_FORMAT(p.tgl_pembelian, '%Y-%m-%d') = \"" +tgl+"\"";
            }else{
                query = "SELECT dp.kode_barang,\n" +
                    "b.nama_barang,\n" +
                    "dp.jumlah_barang,\n" +
                    "kv.nama_konversi,\n" +
                    "dp.hj1,\n" +
                    "dp.hj2,\n" +
                    "kk.nama_kelompok,\n" +
                    "p.tgl_pembelian\n" +
                    "FROM detail_pembelian dp\n" +
                    "JOIN barang b on b.kode_barang = dp.kode_barang\n" +
                    "JOIN barang_konversi bkv on bkv.kode_barang_konversi = dp.kode_konversi\n" +
                    "JOIN konversi kv on kv.kode_konversi = bkv.kode_konversi\n" +
                    "JOIN pembelian p on p.no_faktur_pembelian=dp.no_faktur_pembelian\n" +
                    "JOIN kelompok kk on kk.id_kelompok = b.id_kelompok\n"
                        + "where DATE_FORMAT(p.tgl_pembelian, '%Y-%m-%d') = \"" +tgl+"\"";                
            }
        }
        String Path_Laporan = "/src/Laporan/laporan_barang_datang.jrxml";
        InputStream is = null;
            try {
                is = getClass().getResourceAsStream(Path_Laporan);
            Connect koneksi = new Connect();
           Connection conn = koneksi.conn;
            JasperDesign jd =JRXmlLoader.load(new File("").getAbsolutePath()+Path_Laporan);
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(query);
            jd.setQuery(newQuery);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            
            JasperPrint print = JasperFillManager.fillReport(jr, params,conn);
            //JasperPrintManager.printReport(print, false);
            JasperViewer viewer = new JasperViewer(print);
            System.out.println("sukses");
            jPanel1.removeAll();
            jPanel1.setLayout(new BorderLayout());
            jPanel1.repaint();
            jPanel1.add(new JRViewer(print));

            jPanel1.revalidate();
                System.out.println(query);
            
        } catch (JRException ex) {
            Logger.getLogger(Toko_Laporan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void loadNamaKelompok(){
        System.out.println("load Nama Kelompok");
        try {
            String sql="SELECT k.nama_kelompok FROM kelompok k";
            java.sql.Connection conn = (Connection) Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                String name = res.getString(1);
                comKelompok.addItem(name);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Eror" + e);
        }
    }
    
    private void jButton2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyTyped
        if (evt.getKeyCode()==0) {
            lihat();
        }
    }//GEN-LAST:event_jButton2KeyTyped

    private void tgl_akhirPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tgl_akhirPropertyChange
        if ("date".equals(evt.getPropertyName()))
        {
            awal = tgl_awal.getDate();
            akhir = (Date) evt.getNewValue();
            awal1 = formatTanggal.format(awal);
            akhir1 = formatTanggal.format(akhir);

            System.out.println(evt.getPropertyName()
                + ": " + (Date) evt.getNewValue());


        }
    }//GEN-LAST:event_tgl_akhirPropertyChange

    private void tgl_akhirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tgl_akhirKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            comKelompok.requestFocusInWindow();
        }
    }//GEN-LAST:event_tgl_akhirKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
                /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Master_BarangDatang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Master_BarangDatang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Master_BarangDatang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Master_BarangDatang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Master_BarangDatang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comKelompok;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private com.toedter.calendar.JDateChooser tgl_akhir;
    private com.toedter.calendar.JDateChooser tgl_awal;
    // End of variables declaration//GEN-END:variables
}
