/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Class.Koneksi;
import static UI.Pembelian_LaporanFaktur.rptabelkembali;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Pembelian_LaporanReturn extends javax.swing.JFrame {

    private SimpleDateFormat formatTanggal;
    private Date tglHariIni, awal,akhir;
    /**
     * Creates new form NewJFrame
     */
    public Pembelian_LaporanReturn() {
        initComponents();
        this.setLocationRelativeTo(null);
        tglHariIni = new Date();
        formatTanggal = new SimpleDateFormat("yyyy-MM-dd");
        tglAwal.setDate(tglHariIni);
        tglAkhir.setDate(tglHariIni);
        loadTable();
        loadNoFaktur();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        tglAwal = new com.toedter.calendar.JDateChooser();
        tglAkhir = new com.toedter.calendar.JDateChooser();
        jLabel25 = new javax.swing.JLabel();
        lbl_refresh = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        comNoFaktur = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.lightGray));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Laporan Faktur Return");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "No Faktur", "Jenis Return", "Tanggal", "Supplier", "Kota", "Total", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.math.BigDecimal.class, java.math.BigDecimal.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setText("Kriteria");

        tglAwal.setDateFormatString(" yyyy - M - d");

        tglAkhir.setDateFormatString(" yyyy - M - d");
        tglAkhir.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tglAkhirPropertyChange(evt);
            }
        });
        tglAkhir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tglAkhirKeyPressed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setText("s.d.");

        lbl_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/005-refresh-3.png"))); // NOI18N
        lbl_refresh.setText("Refresh");
        lbl_refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_refreshMouseClicked(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel24.setText("Tanggal");

        comNoFaktur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Masukkan No Faktur Return --" }));
        comNoFaktur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                comNoFakturKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(26, 26, 26)
                        .addComponent(comNoFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tglAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(tglAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(lbl_refresh)))
                .addContainerGap(391, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comNoFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tglAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_refresh)
                                .addComponent(tglAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(979, 510));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        Pembelian_Return pr=new Pembelian_Return();
        pr.setVisible(true);
        pr.setFocusable(true);
    }//GEN-LAST:event_jTable2MouseClicked

    private void tglAkhirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tglAkhirKeyPressed
        if (evt.getKeyCode() == 10) {
            lbl_refresh.requestFocus();
        }
    }//GEN-LAST:event_tglAkhirKeyPressed

    private void lbl_refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_refreshMouseClicked
        loadTable();
        String noFakture = comNoFaktur.getSelectedItem().toString().trim();
        loadNoFaktur();
        System.out.println(noFakture);
        comNoFaktur.setSelectedItem(noFakture);
    }//GEN-LAST:event_lbl_refreshMouseClicked

    private void comNoFakturKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comNoFakturKeyTyped
        if (evt.getKeyCode()==0) {
            jLabel1.requestFocusInWindow();
        }
        System.out.println(evt.getKeyCode()+" = "+KeyEvent.VK_ENTER);
    }//GEN-LAST:event_comNoFakturKeyTyped

    private void tglAkhirPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tglAkhirPropertyChange
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        System.out.println(sdf.format(tglAkhir.getDate()));
        loadNoFaktur();
    }//GEN-LAST:event_tglAkhirPropertyChange

    private void loadNoFaktur(){
        comNoFaktur.removeAllItems();
        comNoFaktur.addItem("-- Masukkan No Faktur Return --");
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        System.out.println("load faktur");
        String tglHariDalem = sdf.format(tglHariIni.getDate());
        String tglAwalDalem = sdf.format(tglAwal.getDate());
        String tglAkhirDalem = sdf.format(tglAkhir.getDate());
        boolean stsHari = tglAwalDalem.equals(tglAkhirDalem);
        try {
            String sql="SELECT prp.no_faktur_return_pakai\n" +
                "FROM pembelian_return_pakai prp\n" +
                "JOIN pembelian_detail_return_pakai pdrp on pdrp.no_faktur_return_pakai = prp.no_faktur_return_pakai\n" +
                "JOIN supplier s on s.kode_supplier=prp.kode_supplier\n"+ 
                (stsHari ? " Where DATE_FORMAT(prp.tgl_return_pakai, '%Y-%m-%d') ='"+tglAwalDalem+"'" : 
                    "Where DATE_FORMAT(prp.tgl_return_pakai, '%Y-%m-%d') between '" + tglAwalDalem + "' and '" + tglAkhirDalem + "'")+
                "\nGROUP BY prp.no_faktur_return_pakai";
            System.out.println("Load No Faktur\n"+sql);
            System.out.println(" - - - - - - - - - - - ");
            java.sql.Connection conn = (Connection) Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while (res.next()) {
                String name = res.getString(1);
                comNoFaktur.addItem(name);
            }
            
            
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Eror" + e.getMessage()+" = ");
        }
    }
    
    public void removeRow() {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        int row = jTable2.getRowCount();
        for (int i = 0; i < row; i++) {
            model.removeRow(0);
        }
    }
    public void loadTable() {
        removeRow();
        String nofakture = comNoFaktur.getSelectedItem().toString().trim();
        System.out.println("Dari load table = "+nofakture);
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tglAwalDalem = sdf.format(tglAwal.getDate());
        String tglAkhirDalem = sdf.format(tglAkhir.getDate());
        String tglHariDalem = sdf.format(tglHariIni.getDate());
        //  System.out.println("" + sdf.format(tglAwal.getDate()));
        
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        
        boolean stsHari = tglAwalDalem.equals(tglAkhirDalem);
        boolean stsFaktur = nofakture.equals("-- Masukkan No Faktur Return --");
        DecimalFormat myFormatter = new DecimalFormat("###,###,##0"); 
        int i = 0;
        try {
            String sql = "SELECT prp.no_faktur_return_pakai,\n" +
"               prp.jenis_return,\n" +
"               prp.tgl_return_pakai,\n" +
"               s.nama_supplier,\n" +
"               s.kota_supplier,\n" +
"               pdrp.harga_pembelian,\n" +
"               pdrp.jumlah_barang,\n" +
"               pdrp.harga_pembelian * pdrp.jumlah_barang total\n" +
"               from pembelian_return_pakai prp\n" +
"               JOIN pembelian_detail_return_pakai pdrp on pdrp.no_faktur_return_pakai = prp.no_faktur_return_pakai\n" +
"               JOIN supplier s on s.kode_supplier=prp.kode_supplier\n"+ 
                (stsHari ? " Where DATE_FORMAT(prp.tgl_return_pakai, '%Y-%m-%d') ='"+tglAwalDalem+"'" : 
                    "Where DATE_FORMAT(prp.tgl_return_pakai, '%Y-%m-%d') between '" + tglAwalDalem + "' and '" + tglAkhirDalem + "'")+
                (stsFaktur ? "":"\nAND prp.no_faktur_return_pakai = '"+nofakture+"'")
                    ;
            Connection conn = (Connection) Koneksi.configDB();
            Statement stat = conn.createStatement();
            ResultSet res = stat.executeQuery(sql);
            Object temps[] = new Object[8];
            int saldo =0;
            while (res.next()) {
                model.addRow(new Object[]{
                    i++,
                    res.getString("no_faktur_return_pakai"),
                    res.getString("jenis_return"),
                    dotConverter(sdf.format(res.getDate("tgl_return_pakai"))),
                    res.getString("nama_supplier"),
                    res.getString("kota_supplier"),
                    myFormatter.format(res.getInt("total")),
                    myFormatter.format(saldo = saldo+ res.getInt("total"))
                });
                
            }
            conn.close();
            System.out.println("Load table\n"+sql);
            System.out.println(" - - - - - - - - - - - ");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Eror = " + e);
        }
    }
    
    static String dotConverter(String b) {
        b = b.replace(".0", "");
        return b;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
                /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembelian_LaporanReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembelian_LaporanReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembelian_LaporanReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembelian_LaporanReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembelian_LaporanReturn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comNoFaktur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbl_refresh;
    private com.toedter.calendar.JDateChooser tglAkhir;
    private com.toedter.calendar.JDateChooser tglAwal;
    // End of variables declaration//GEN-END:variables
}
