/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Java.Connect;
import java.awt.BorderLayout;
import java.io.File;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author USER
 */
public class Sales_Omzet extends javax.swing.JFrame {

    /**
     * Creates new form Sales_omzet
     */
    private SimpleDateFormat formatTanggal;
    private Date tglHariIni, awal,akhir;
    
    public Sales_Omzet() {
        initComponents();
        this.setLocationRelativeTo(null);
        tglHariIni = new Date();
        formatTanggal = new SimpleDateFormat("yyyy-MM-dd");
        tgl_awal.setDate(tglHariIni);
        tgl_akhir.setDate(tglHariIni);
        cek();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel66 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        tgl_awal = new com.toedter.calendar.JDateChooser();
        tgl_akhir = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        jPanel66.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, null));
        jPanel66.setForeground(new java.awt.Color(51, 51, 51));

        jCheckBox1.setText("Tanggal");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });

        tgl_awal.setDateFormatString("dd-MM-yyyy");
        tgl_awal.setEnabled(false);

        tgl_akhir.setDateFormatString("dd-MM-yyyy");
        tgl_akhir.setEnabled(false);

        jButton1.setText("Lihat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel66Layout = new javax.swing.GroupLayout(jPanel66);
        jPanel66.setLayout(jPanel66Layout);
        jPanel66Layout.setHorizontalGroup(
            jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel66Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tgl_awal, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(tgl_akhir, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel66Layout.setVerticalGroup(
            jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel66Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox1)
                        .addComponent(jButton1))
                    .addGroup(jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tgl_awal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tgl_akhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 801, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel66, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        if (jCheckBox1.isSelected()) {
            tgl_awal.setEnabled(true);
            tgl_akhir.setEnabled(true);
            System.out.println("cekbox enabled");
        }else{
            String tgl = formatTanggal.format(tglHariIni);
            tgl_awal.setEnabled(false);
            tgl_akhir.setEnabled(false);
            tgl_awal.setDate(tglHariIni);
            tgl_akhir.setDate(tglHariIni);
            cek();
        }
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Date awalDalem = tgl_awal.getDate();
        Date akhirDalem = tgl_akhir.getDate();
        HashMap params = new HashMap<String, Date>();
        String awal1Dalem = formatTanggal.format(awalDalem);
        String akhir1Dalem = formatTanggal.format(akhirDalem);
        boolean status = jCheckBox1.isSelected();
        
        params.put("awal", awalDalem);
        params.put("akhir", akhirDalem);
        String query = "select sl.kode_salesman,\n" +
            "sl.nama_salesman,\n" +
            "SUM(pjd.jumlah_barang*pjd.harga_jual) total_jual,\n" +
            "SUM(pjd.jumlah_barang*pjd.hpp) total_hpp,\n" +
            "pj.tgl_penjualan\n" +
            "from penjualan pj\n" +
            "join penjualan_detail pjd on pjd.no_faktur_penjualan = pj.no_faktur_penjualan\n" +
            "join customer c on c.kode_customer = pj.kode_customer\n" +
            "JOIN salesman sl on sl.kode_salesman = pj.kode_salesman\n" +
            "Where DATE_FORMAT(pj.tgl_penjualan, '%Y-%m-%d') BETWEEN \""+awal1Dalem+"\" and \""+akhir1Dalem+"\"\n" +
            "GROUP BY sl.kode_salesman\n" +
            "order by sl.nama_salesman, c.nama_customer,pj.no_faktur_penjualan asc";
        loadLaporan(query, params);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cek(){
        String tgl = formatTanggal.format(tglHariIni);
        String query = "select sl.kode_salesman,\n" +
            "sl.nama_salesman,\n" +
            "SUM(pjd.jumlah_barang*pjd.harga_jual) total_jual,\n" +
            "SUM(pjd.jumlah_barang*pjd.hpp) total_hpp,\n" +
            "pj.tgl_penjualan\n" +
            "from penjualan pj\n" +
            "join penjualan_detail pjd on pjd.no_faktur_penjualan = pj.no_faktur_penjualan\n" +
            "join customer c on c.kode_customer = pj.kode_customer\n" +
            "JOIN salesman sl on sl.kode_salesman = pj.kode_salesman\n" +
            " Where DATE_FORMAT(pj.tgl_penjualan, '%Y-%m-%d') = \"" +tgl+"\""+
            "GROUP BY sl.kode_salesman\n" +
            "order by sl.nama_salesman, c.nama_customer,pj.no_faktur_penjualan asc";
        loadLaporan(query, null);
    }
    
    private void loadLaporan(String query, HashMap params){
        try {
            Connect koneksi = new Connect();
            Connection conn = koneksi.conn;
            JasperDesign jd =JRXmlLoader.load(new File("").getAbsolutePath()+"/src/Laporan/sales_omzet.jrxml");
            
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(query);
            jd.setQuery(newQuery);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            JasperPrint print = JasperFillManager.fillReport(jr, params,conn);;
            JasperViewer viewer = new JasperViewer(print);
            System.out.println("sukses");
            jPanel1.removeAll();
            jPanel1.setLayout(new BorderLayout());
            jPanel1.repaint();
            jPanel1.add(new JRViewer(print));
////            show_report.repaint();
            jPanel1.revalidate();
        } catch (JRException ex) {
                System.out.println("error = "+ex.getMessage());
            Logger.getLogger(Laporan_Penjualan.class.getName()).log(Level.SEVERE, null, ex);
        } catch(Exception ex){
                System.out.println(ex.getMessage());
            Logger.getLogger(Laporan_Penjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sales_Omzet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sales_Omzet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sales_Omzet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sales_Omzet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sales_Omzet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel66;
    private com.toedter.calendar.JDateChooser tgl_akhir;
    private com.toedter.calendar.JDateChooser tgl_awal;
    // End of variables declaration//GEN-END:variables
}
